<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head>  
	<?php echo $this->headMeta()
	      ->setHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
	      ->setHttpEquiv('Content-Style-Type', 'text/css')
	      ->setHttpEquiv('lang', 'fr')
	      ->setName('author', 'Nittel Romain')
	      ->setName('language', 'fr'); ?>
 	<?php echo $this->headTitle('DRAW WEB'); ?>
  	<meta name="description" content=""/>
	<meta name="keywords" content=""/>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
</head>
<body>
    
</body>
</html>

